---
deployment:
  tasks:
    - export DEPLOYPATH=/home/univvwcw/public_html/babers-saloon
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -r /home/univvwcw/babers-saloon/backend $DEPLOYPATH
    - /bin/cp /home/univvwcw/babers-saloon/package-lock.json $DEPLOYPATH
    - /bin/cp /home/univvwcw/babers-saloon/package.json $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/tmp
    - /bin/touch $DEPLOYPATH/tmp/restart.txt
    - source /home/univvwcw/nodevenv/babers-saloon/14/bin/activate
    - cd /home/univvwcw/babers-saloon
    - npm install
