---
deployment:
  tasks:
    - export DEPLOYPATH=/home/codeiroside/public_html/babers-saloon
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -r /home/codeiroside/repositories/babers-saloon/backend $DEPLOYPATH
    - /bin/cp /home/codeiroside/repositories/babers-saloon/package-lock.json $DEPLOYPATH
    - /bin/cp /home/codeiroside/repositories/babers-saloon/package.json $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/tmp
    - /bin/touch $DEPLOYPATH/tmp/restart.txt
    - npm install
    - npm start
